# Generated by Django 5.2 on 2025-05-02 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=100, verbose_name='Тип сущности')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID сущности')),
                ('action', models.CharField(choices=[('create', 'Создания'), ('update', 'Редактирование'), ('delete', 'Удаление')], max_length=15, verbose_name='Действие')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время')),
                ('changes', models.JSONField(default=dict, verbose_name='Детали изменений')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История изменений',
                'verbose_name_plural': 'Истории изменений',
                'indexes': [models.Index(fields=['timestamp'], name='analytics_h_timesta_063660_idx')],
            },
        ),
    ]
