version: "3.8"

services:
  db:
    image: postgres:16
    container_name: postgres16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5433:5432"
  backend:
    build: .
    restart: always
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - .:/app
    ports:
      - "8008:8008"

  tg_bot:
    build:
      context: .
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
    command:
      - poetry run python -m telegram_bot.bot

volumes:
  postgres_data: