# Generated by Django 5.2 on 2025-04-30 13:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Категория')),
                ('is_colored', models.BooleanField(default=False, verbose_name='Цветной')),
                ('color_type', models.CharField(blank=True, max_length=50, verbose_name='Тип цвета')),
                ('block_rate', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ставка за блок')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество (шт)')),
                ('production_date', models.DateField(verbose_name='Дата производства')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': ('Партия производства',),
                'verbose_name_plural': 'Партии производства',
            },
        ),
        migrations.CreateModel(
            name='SubBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество (шт)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('employees', models.ManyToManyField(to='employees.employees', verbose_name='Сотрудники')),
                ('production_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.productionbatch', verbose_name='Партия')),
            ],
            options={
                'verbose_name': 'Подпартия',
                'verbose_name_plural': 'Подпартии',
            },
        ),
        migrations.AddIndex(
            model_name='productionbatch',
            index=models.Index(fields=['production_date'], name='production__product_1fdeef_idx'),
        ),
    ]
