# Generated by Django 5.2 on 2025-05-03 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_product_price_per_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionbatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.product', verbose_name='Категория'),
        ),
    ]
