# Generated by Django 5.2 on 2025-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_payment_status_alter_order_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='advance_payment',
        ),
        migrations.AddField(
            model_name='payment',
            name='for_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='К оплате'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('advance', 'Аванс'), ('final', 'Окончательный')], default='advance', max_length=20, verbose_name='Тип платежа'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-05-01', verbose_name='Дата обновления'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Ожидания оплаты'), ('partial', 'Частично'), ('paid', 'Оплачено')], default='pending', max_length=20, verbose_name='Статус оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Общее количество'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_type'], name='orders_paym_payment_64e807_idx'),
        ),
    ]
