# Generated by Django 5.2 on 2025-05-12 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_advance_payment_payment_for_payment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='orders_paym_payment_64e807_idx',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='for_payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_type',
        ),
        migrations.AddField(
            model_name='order',
            name='initial_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Частичная оплата'),
        ),
    ]
