# Generated by Django 5.2 on 2025-04-30 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('RED SAND', 'Красный песок'), ('GRAVEL', 'Щебень'), ('CEMENT', 'Цемент'), ('FINE SAND', 'Измельченный песок')], max_length=50, verbose_name='Тип материала')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество (тонны)')),
                ('delivery_date', models.DateField(verbose_name='Дата поставки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'indexes': [models.Index(fields=['delivery_date'], name='materials_m_deliver_e6d3c3_idx')],
            },
        ),
    ]
