# Generated by Django 5.2 on 2025-05-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='name',
            field=models.CharField(choices=[('RED SAND', 'Красный песок'), ('GRAVEL', 'Щебень'), ('CEMENT', 'Цемент'), ('FINE SAND', 'Измельченный песок'), ('PAINT', 'Краска')], max_length=50, verbose_name='Тип материала'),
        ),
    ]
