# Generated by Django 5.2 on 2025-05-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_owner',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telegram_id',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Разработчик'), ('owner', 'Владелец'), ('admin', 'Админ')], default='admin', max_length=15, verbose_name='Роль'),
        ),
    ]
