# Generated by Django 5.2 on 2025-05-02 09:42
from django.utils import timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Добавлен'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='phone',
            field=models.CharField(blank=True, max_length=14, verbose_name='Номер телефона'),
        ),
    ]
