# Generated by Django 5.2 on 2025-05-03 09:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_created_at_employees_phone'),
        ('production', '0003_alter_productionbatch_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Дата выплаты')),
                ('payment_status', models.CharField(choices=[('not paid', 'Не оплачено'), ('paid', 'Оплачено')], default='not paid', max_length=15, verbose_name='Статус оплаты')),
                ('calculation_date', models.DateField(verbose_name='Дата расчета')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Дата создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees', verbose_name='Работник')),
                ('sub_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.subbatch', verbose_name='Подпартия')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'verbose_name_plural': 'Зарплаты',
                'indexes': [models.Index(fields=['paid_date'], name='employees_s_paid_da_a906cd_idx'), models.Index(fields=['employee', 'paid_date'], name='employees_s_employe_684662_idx')],
            },
        ),
    ]
