# Generated by Django 5.2 on 2025-05-12 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_alter_salary_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес сотрудника'),
        ),
    ]
